{
 "title": "EaC Governance Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GitOps Compliance Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\ncount(argocd_app_info{sync_status=\"Synced\"})\r\n/\r\ncount(argocd_app_info)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitOps Drift",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{sync_status=\"OutOfSync\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gatekeeper Policy Denials Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(gatekeeper_validation_request_count_total{admission_status=\"deny\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Denied Admission Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_validation_request_count_total{admission_status=\"deny\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}